FROM node:20-alpine AS runner

ENV NODE_ENV=production

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY node_modules ./node_modules
COPY packages ./packages
COPY services ./services

CMD ["sh", "-c", "cd /app/${SERVICE_DIR} && node dist/main.js"]
